### PR TITLE
use default value of parameters from dashboard

### LINKED ISSUE #16: Default parameter values aren't accepted in GUI
In the command-handler-invocation interface, a default value is populated for a required parameter. But if I don't change it, I get an error. `message: "Error: Parameter 'sourceBranch' required but missing in invocation to 'NpmCascadeBuild'"` for instance.

### PR DESCRIPTION
**Pull request by jessitron**
fixes #16

### CODE REVIEW

**Comment by cdupuis** [comment]
Pull request auto merge enabled by @cdupuis. [atomist:enable-auto-merge]

**Comment by jessitron** [comment]
will it automerge ??

**Comment by slimslenderslacks** [comment]
Pull request auto merged by Atomist.

* 1 approved review by @cdupuis
* 4 successful checks

**Comment by jessitron** [comment]
was that the real Jim, or the Atomist Jim ??

**Comment by cdupuis** [comment]
no, that was the bot token.

**Pull request merged**
