### PR TITLE
Store user config in correct directory on Windows

### PR DESCRIPTION
**Pull request by jwalter**

### CODE REVIEW

**Comment by ddgenome** [comment]
Let me try to get the build green and then we can merge this.

**Comment by jwalter** [comment]
Not much I can do to fix the build I suppose: "Pull requests sent from forked repositories do not have access to encrypted variables or data."
(https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)

**Comment by ddgenome** [comment]
Yeah, that's what I'm trying to find a way to work around.

**Comment by ddgenome** [comment]
It's clearly not your changes that are the issue!

**Comment by ddgenome** [comment]
I had to delint some things but after that everything passes. Since I can't push to your fork, I am just going to merge this PR and then make the necessary changes. Thanks again!

**Pull request merged**
